version: "3.9"

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-authkey
    hostname: banana
    environment:
      - TS_AUTHKEY=tskey-auth-ku3fJuJCGz11CNTRL-hDFSVYNrCEFZtBJbDhefEFsCiNB7jbBrU
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  app:
    build: .
    network_mode: service:tailscale
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=phuctnh
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:11.4
    network_mode: service:tailscale
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=phuctnh
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  tailscale-state:
  mariadb_data:
