version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: phuctnh123
      MYSQL_DATABASE: mcu
    ports:
      - "4444:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    image: phuctnh03/mcu-learning-test
    depends_on:
      - db
    ports:
      - "5555:5555" # REST API
      - "5050:5050" # WebSocket
    command: [ "/wait-for-it.sh", "db:3306", "--", "python", "main.py" ]

volumes:
  mysql_data:
